name: reporta_fallas
description: "A new Flutter project."

publish_to: 'none' # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^2.10.0
  cloud_firestore: ^4.7.1 
  firebase_storage: ^11.2.2
  geolocator: ^9.0.2
  image_picker: ^0.8.7+3
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
